"""
Synthetic Data Generation Module for GlucoTwin.

DISCLAIMER:
All data generated by this module are purely synthetic and intended solely for
research, demonstration, and proof-of-concept purposes. No real patient data
or Personally Identifiable Information (PII) is used.
"""

import numpy as np
import pandas as pd
from datetime import datetime, timedelta
from pathlib import Path
from typing import Tuple, Dict, List
import yaml

from src.utils.logger import get_logger
from src.utils.config_loader import load_config

logger = get_logger("SyntheticDataGen")

def generate_ehr_profiles(n_patients: int = 50, seed: int = 42) -> pd.DataFrame:
    """
    Generates synthetic static EHR data for n_patients.
    """
    np.random.seed(seed)
    patient_ids = [f"PAT-{i+1:03d}" for i in range(n_patients)]
    
    ages = np.random.randint(22, 75, size=n_patients)
    sexes = np.random.choice(["M", "F"], size=n_patients, p=[0.51, 0.49])
    bmis = np.round(np.random.normal(28.5, 5.0, size=n_patients).clip(18.5, 45.0), 1)
    
    # HbA1c correlated with BMI and age
    hba1c_base = 4.8 + (bmis - 20) * 0.12 + (ages - 30) * 0.02 + np.random.normal(0, 0.5, n_patients)
    hba1c = np.round(hba1c_base.clip(5.0, 11.5), 1)
    
    diabetes_statuses = []
    medications = []
    diabetes_durations = []
    
    for h, b in zip(hba1c, bmis):
        if h < 5.7:
            status = "No Diabetes"
            med = "None"
            dur = 0.0
        elif h < 6.5:
            status = "Pre-Diabetes"
            med = np.random.choice(["None", "Metformin"], p=[0.7, 0.3])
            dur = np.round(np.random.uniform(0.5, 3.0), 1)
        else:
            status = np.random.choice(["Type 1", "Type 2"], p=[0.15, 0.85])
            if status == "Type 1":
                med = "Insulin"
            else:
                med = np.random.choice(["Metformin", "Metformin+DPP4", "Insulin+Metformin", "Insulin"], p=[0.4, 0.3, 0.2, 0.1])
            dur = np.round(np.random.uniform(1.0, 20.0), 1)
            
        diabetes_statuses.append(status)
        medications.append(med)
        diabetes_durations.append(dur)
        
    hypertension = np.random.binomial(1, p=(bmis > 28) * 0.4 + 0.2)
    cholesterol = np.random.choice(["Normal", "High"], size=n_patients, p=[0.55, 0.45])
    family_risk_score = np.round(np.random.uniform(0.1, 0.9, size=n_patients), 2)
    
    ehr_df = pd.DataFrame({
        "patient_id": patient_ids,
        "age": ages,
        "sex": sexes,
        "bmi": bmis,
        "hba1c": hba1c,
        "diabetes_status": diabetes_statuses,
        "hypertension": hypertension,
        "cholesterol": cholesterol,
        "medication": medications,
        "diabetes_duration_years": diabetes_durations,
        "family_risk_score": family_risk_score
    })
    
    return ehr_df

def generate_wearable_timeseries(
    ehr_df: pd.DataFrame,
    days: int = 14,
    interval_minutes: int = 15,
    seed: int = 42
) -> pd.DataFrame:
    """
    Generates synthetic 15-minute resolution wearable time series for all patients in ehr_df.
    Incorporate circadian rhythms, meals, exercise, sleep deficit, and physiological coupling.
    """
    np.random.seed(seed)
    start_date = datetime(2026, 1, 1, 0, 0, 0)
    intervals_per_day = (24 * 60) // interval_minutes
    total_intervals = days * intervals_per_day
    
    timestamps = [start_date + timedelta(minutes=i * interval_minutes) for i in range(total_intervals)]
    
    all_series = []
    
    for _, patient in ehr_df.iterrows():
        p_id = patient["patient_id"]
        hba1c = patient["hba1c"]
        bmi = patient["bmi"]
        med = patient["medication"]
        status = patient["diabetes_status"]
        
        # Patient baseline glucose (mg/dL)
        baseline_glucose = 75 + (hba1c - 5.0) * 18 + (bmi - 22) * 0.8
        if "Insulin" in med:
            baseline_glucose -= 10
            
        # Daily sleep pattern (generated once per day per patient)
        daily_sleep = np.random.normal(7.2 - (bmi > 30)*0.5, 0.9, size=days).clip(4.0, 9.5)
        
        # State tracking for continuous autoregressive modeling
        curr_g = baseline_glucose
        carbs_in_stomach = 0.0
        
        p_records = []
        
        for idx, ts in enumerate(timestamps):
            day_idx = idx // intervals_per_day
            hour = ts.hour + ts.minute / 60.0
            sleep_hrs = round(daily_sleep[day_idx], 1)
            sleep_deficit = max(0.0, 8.0 - sleep_hrs)
            
            # Meals schedule (Breakfast ~8am, Lunch ~1pm, Dinner ~7pm, Snack random)
            meal_carbs = 0.0
            meal_type = "None"
            
            if ts.minute == 0 or ts.minute == 30:
                if 7.5 <= hour <= 8.5 and np.random.rand() < 0.35:
                    meal_carbs = np.random.choice([30, 45, 60, 75])
                    meal_type = "Breakfast"
                elif 12.5 <= hour <= 13.5 and np.random.rand() < 0.35:
                    meal_carbs = np.random.choice([40, 60, 80, 100])
                    meal_type = "Lunch"
                elif 18.5 <= hour <= 19.5 and np.random.rand() < 0.35:
                    meal_carbs = np.random.choice([45, 70, 90, 110])
                    meal_type = "Dinner"
                elif np.random.rand() < 0.05:
                    meal_carbs = np.random.choice([15, 25, 35])
                    meal_type = "Snack"
                    
            if meal_carbs > 0:
                carbs_in_stomach += meal_carbs
                
            # Digestion impact on glucose
            digested = carbs_in_stomach * 0.18
            carbs_in_stomach -= digested
            
            # Insulin response strength (lower sensitivity for higher HbA1c/BMI/sleep deficit)
            insulin_sensitivity = max(0.15, 1.0 - (hba1c - 5.0)*0.08 - sleep_deficit*0.05)
            glucose_gain = digested * (1.2 / insulin_sensitivity)
            
            # Activity level & Steps
            is_sleeping = (0.0 <= hour < 6.5) or (hour > 23.0)
            if is_sleeping:
                steps = np.random.randint(0, 10)
                activity = "Sedentary"
                base_hr = 58.0 - (sleep_hrs - 7)*2
            else:
                # Occasional exercise
                if 17.0 <= hour <= 18.0 and np.random.rand() < 0.2:
                    steps = np.random.randint(1200, 2500)
                    activity = "Vigorous"
                elif np.random.rand() < 0.25:
                    steps = np.random.randint(300, 900)
                    activity = "Moderate"
                elif np.random.rand() < 0.5:
                    steps = np.random.randint(50, 300)
                    activity = "Light"
                else:
                    steps = np.random.randint(0, 50)
                    activity = "Sedentary"
                base_hr = 70.0 + (bmi - 25)*0.5 + (steps / 100.0)*2.5
                
            # Glucose clearance from activity
            clearance = (steps / 1000.0) * 4.0 * insulin_sensitivity
            
            # Basal regulation drift towards baseline
            drift = (baseline_glucose + sleep_deficit * 3.0 - curr_g) * 0.08
            
            # Update glucose state
            curr_g = curr_g + glucose_gain - clearance + drift + np.random.normal(0, 1.5)
            curr_g = max(55.0, min(380.0, curr_g))
            
            # Heart rate and HRV simulation
            heart_rate = round(base_hr + (curr_g - baseline_glucose)*0.05 + np.random.normal(0, 2.0), 1)
            # HRV (RMSSD in ms) decreases with HR, high glucose, and sleep deficit
            hrv_base = 65.0 - (patient["age"] - 20)*0.4 - (bmi - 22)*0.6
            hrv = max(12.0, round(hrv_base - (heart_rate - 60)*0.4 - sleep_deficit*2.5 + np.random.normal(0, 3.0), 1))
            
            p_records.append({
                "patient_id": p_id,
                "timestamp": ts,
                "glucose": round(curr_g, 1),
                "heart_rate": heart_rate,
                "hrv": hrv,
                "steps": int(steps),
                "sleep_hours": sleep_hrs,
                "activity_level": activity,
                "meal_carbs": float(meal_carbs),
                "meal_type": meal_type
            })
            
        all_series.extend(p_records)
        
    wearable_df = pd.DataFrame(all_series)
    return wearable_df

def generate_and_save_data(config_path: str = None) -> Tuple[pd.DataFrame, pd.DataFrame]:
    """
    Main function to generate and save EHR and Wearable synthetic datasets.
    """
    config = load_config(config_path)
    synth_cfg = config["synthetic_generation"]
    
    n_patients = synth_cfg.get("n_patients", 50)
    days = synth_cfg.get("days_per_patient", 14)
    interval = synth_cfg.get("interval_minutes", 15)
    seed = synth_cfg.get("random_seed", 42)
    
    ehr_path = Path(config["paths"]["ehr_file"])
    wearable_path = Path(config["paths"]["wearable_file"])
    
    ehr_path.parent.mkdir(parents=True, exist_ok=True)
    wearable_path.parent.mkdir(parents=True, exist_ok=True)
    
    logger.info(f"Generating synthetic EHR profile for {n_patients} patients...")
    ehr_df = generate_ehr_profiles(n_patients=n_patients, seed=seed)
    
    logger.info(f"Generating synthetic wearable time series ({days} days, {interval}-min intervals)...")
    wearable_df = generate_wearable_timeseries(ehr_df, days=days, interval_minutes=interval, seed=seed)
    
    logger.info(f"Saving EHR dataset to {ehr_path} (Shape: {ehr_df.shape})")
    ehr_df.to_csv(ehr_path, index=False)
    
    logger.info(f"Saving Wearable dataset to {wearable_path} (Shape: {wearable_df.shape})")
    wearable_df.to_csv(wearable_path, index=False)
    
    return ehr_df, wearable_df

if __name__ == "__main__":
    generate_and_save_data()
